global:                                                                         
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:                                                              
      monitor: 'exporter-metrics'                                                

scrape_configs:

- job_name: 'push-metrics'
  dns_sd_configs:
  - names:
    - pushgateway
    refresh_interval: 15s
    type: A
    port: 9091

- job_name: 'Prometheus'
  static_configs:
    - targets:
      - '127.0.0.1:9090'
